# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 353f4ad8427afdf33222d545bb626eac755941046f0ce919272167baa349658536543182c310820da1ba3305381450d95d63ca8ac335813cbff4136ca89d8706

test:
  secret_key_base: 869e61423639cad0bdc27107c0418261b8cbad28609ffd3b1767b8b4e733555fc3d8d90e3577919aeccb949414cd488fec0e58c21725a322a649fc744fa1f703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
